SUBJECTS = {
"Electrical Fundamentals":{"icon":"⚡","description":"Core quantities, circuit laws, network analysis, AC theory and transient response.","topics":["Charge, current, voltage and energy","Ohm's law and resistance","Series/parallel circuits","Kirchhoff's laws","Power and energy","Node-voltage and mesh-current methods","Network theorems","Capacitance and inductance","AC waveforms and RMS","Phasors and impedance","Resonance and filters","First-order transients"]},
"Power Systems":{"icon":"🔌","description":"Generation, transmission, distribution, three-phase power, fault studies and reliability.","topics":["Three-phase systems","Transformers and substations","Per-unit system","Transmission and distribution","Load-flow fundamentals","Short-circuit calculations","Grounding and earthing","Protection coordination","Power quality","System reliability"]},
"Industrial Automation & Control":{"icon":"🏭","description":"Industrial control architecture, PLCs, sensors, actuators, HMI/SCADA and networks.","topics":["Control-system fundamentals","Relays and contactors","Sensors and actuators","PLC architecture and scan cycle","Ladder logic","Timers/counters","HMI and SCADA","Industrial protocols","VFD control","Commissioning and troubleshooting"]},
"Electrical Machines":{"icon":"⚙️","description":"Magnetic circuits, transformers, motors, generators, performance and maintenance.","topics":["Magnetic circuits","Transformer equivalent circuit","DC machines","Induction motors","Synchronous machines","Motor starting","Losses and efficiency","Nameplate data","Testing and maintenance"]},
"Electronics & Embedded Systems":{"icon":"🔧","description":"Semiconductors, analog/digital electronics, power electronics and embedded control.","topics":["Semiconductor physics","Diodes and rectifiers","BJT and MOSFET","Operational amplifiers","Digital logic","Power converters","Microcontrollers","ADC/PWM","Communication interfaces","EMC and circuit protection"]},
"Installation & Maintenance":{"icon":"🧰","description":"Drawings, installation planning, inspection, testing, preventive maintenance and fault diagnosis.","topics":["Electrical drawings","Cable selection","Wiring systems","Distribution boards","Overcurrent protection","Inspection and testing","Maintenance planning","Fault-finding workflow","Documentation and isolation"]},
"Measurements & Instrumentation":{"icon":"📏","description":"Measurement principles, test instruments, sensor systems, calibration and uncertainty.","topics":["Units and uncertainty","Multimeters and clamp meters","Oscilloscopes","CTs and VTs","Sensors/transducers","4–20 mA loops","Calibration","Process instrumentation","Measurement errors"]},
"Renewable Energy":{"icon":"☀️","description":"Photovoltaics, conversion, storage, system sizing, protection and grid integration.","topics":["Solar resource","PV cell and module","Array configuration","MPPT","Inverters","Battery storage","System sizing","DC/AC protection","Grid connection and monitoring"]},
"Electrical Design & Calculations":{"icon":"📐","description":"Engineering design calculations for loads, cables, voltage drop, protection and documentation.","topics":["Load estimation","Demand/diversity","Cable ampacity","Voltage drop","Short-circuit withstand","Breaker/fuse selection","Power-factor correction","Single-line drawings","Calculation reports"]},
"Control Systems & Drives":{"icon":"🎛️","description":"Dynamic systems, feedback, stability, PID control, VFDs, servo systems and diagnostics.","topics":["Open/closed loop","Transfer functions","Block diagrams","Stability","PID control","Drive architecture","VFD fundamentals","Servo systems","Control-loop troubleshooting"]},
"Electrical Safety & Standards":{"icon":"🦺","description":"Electrical hazards, risk controls, protective measures, safe isolation and standards awareness.","topics":["Shock and arc hazards","Risk assessment","Isolation and lockout/tagout","Protective earthing","Overcurrent/RCD protection","Safe instrument use","PPE and boundaries","Standards awareness","Incident learning"]},
"Marine Electrical & ETO":{"icon":"🚢","description":"Shipboard generation, distribution, automation, emergency systems, maintenance and ETO pathway.","topics":["Shipboard architecture","Generators and switchboards","Parallel generator operation","Power management","Emergency generator/batteries","Marine motors/drives","Alarm monitoring","Navigation/communication overview","Planned maintenance","STCW and certification research"]},
}

def L(subject, level, title, intro, sections, points, question, answer, refs, duration="30–45 minutes", practice=None, safety=None):
    return {"subject":subject,"level":level,"title":title,"intro":intro,"sections":sections,"key_points":points,"question":question,"answer":answer,"references":refs,"duration":duration,"practice":practice,"safety":safety}

LESSONS = [
L("Electrical Fundamentals","Basic","1. Charge, Current, Voltage and Energy",
"Electrical engineering describes charge, energy transfer and the behavior of circuits. Current is the rate of charge flow; voltage is energy transferred per unit charge.",
[
{"heading":"Charge and current","body":"Electric charge is measured in coulombs (C). Current is the time rate of charge flow: I = dQ/dt; for constant current, Q = It. One ampere equals one coulomb per second. Conventional current points in the direction positive charge would move, opposite to electron drift in a metal." ,"example":"If 30 C passes a point in 10 s, I = Q/t = 30/10 = 3 A."},
{"heading":"Voltage and energy","body":"Potential difference is work or energy transferred per unit charge: V = W/Q. The volt equals one joule per coulomb. A source establishes a potential difference; current requires a closed path and a conducting medium."},
{"heading":"Power and energy","body":"Power is the rate of energy transfer, P = dW/dt. For a DC element, P = VI. Using Ohm's law for a resistor gives P = I²R = V²/R. Energy is measured in joules; electrical bills often use kilowatt-hours (1 kWh = 3.6 MJ).","example":"A 60 W lamp operating for 5 h uses 60 × 5 = 300 Wh = 0.3 kWh."},
{"heading":"Circuit model and assumptions","body":"A circuit model combines sources, conductors and loads. Ideal models simplify real devices; actual components have tolerances, temperature limits, parasitic effects and ratings. Always label units and distinguish power (W) from energy (Wh or J)."}
],["Current is charge per time.","Voltage is energy per charge.","Power is energy per time.","A complete circuit path is needed for sustained current.","Check units and equipment ratings."],
"A current of 2.5 A flows for 8 s. Find charge transferred and explain voltage versus current.","Q = It = 2.5 × 8 = 20 C. Current measures charge flow rate; voltage measures energy transferred per unit charge.",
["Hambley, Electrical Engineering: Principles and Applications — introductory circuit quantities.","IEC Electropedia (IEV) terminology."],practice="Calculate the energy in kWh used by a 1.2 kW heater operating for 45 minutes."),
L("Electrical Fundamentals","Basic","2. Ohm's Law and Resistance",
"Ohm's law relates voltage and current for an ohmic element at specified physical conditions. It is a powerful model but not universal for every component.",
[
{"heading":"Ohm's law","body":"For an ohmic resistor, V = IR, so I = V/R and R = V/I. Resistance is measured in ohms (Ω). The V–I curve of an ideal resistor is a straight line through the origin." ,"equation":r"V=IR,\\quad I=\\frac{V}{R},\\quad R=\\frac{V}{I}"},
{"heading":"Physical resistance","body":"For a uniform conductor, R = ρL/A, where ρ is resistivity (Ω·m), L is length (m), and A is cross-sectional area (m²). Longer conductors generally have higher resistance; larger cross-section generally lowers it. Resistivity depends on material and temperature.","example":"For ρ = 1.7×10⁻⁸ Ω·m, L = 10 m, A = 2×10⁻⁶ m²: R = ρL/A ≈ 0.085 Ω."},
{"heading":"Worked circuit","body":"With 12 V across 6 Ω, current is 2 A and resistor power is 24 W. The chosen component must tolerate the heat produced, with appropriate rating and derating." ,"example":"I = 12/6 = 2 A; P = VI = 12×2 = 24 W."},
{"heading":"Non-ohmic devices","body":"Diodes, lamps and semiconductor devices may have nonlinear current-voltage curves. AC circuits also require impedance to represent resistance and reactance. Do not apply a constant-resistance model outside its valid operating range."}
],["Use V = IR only with the correct model and conditions.","R = ρL/A links material, length and area.","Check power dissipation and temperature limits.","Nonlinear devices need their own models."],
"A 24 V supply is applied to an 8 Ω resistor. Find current and power.","I = 24/8 = 3 A. P = VI = 72 W. The resistor must have a suitable power and thermal rating.",
["Hambley — resistive circuits and network analysis."],practice="Compare how resistance changes if conductor length doubles while material and area stay constant."),
L("Electrical Fundamentals","Basic","3. Series and Parallel Networks",
"Series and parallel rules reduce a network to an equivalent resistance and provide a basis for voltage and current division.",
[
{"heading":"Series","body":"In a series path without branching, the same current flows through every element. Equivalent resistance is the sum: Req = R1 + R2 + … . Supply voltage divides across components; for resistors, the drop is proportional to resistance." ,"equation":r"R_{eq}=\\sum_{k=1}^{n}R_k"},
{"heading":"Parallel","body":"Elements are in parallel when they connect across the same two nodes, so each has the same voltage. Reciprocal resistances add. For two resistors, Req = R1R2/(R1+R2). A positive-resistance parallel equivalent is lower than the smallest branch resistance.","equation":r"\\frac{1}{R_{eq}}=\\sum_{k=1}^{n}\\frac{1}{R_k}"},
{"heading":"Worked examples","body":"Series: 4 Ω and 8 Ω across 24 V give Req = 12 Ω, I = 2 A and drops of 8 V and 16 V. Parallel: 6 Ω and 3 Ω give Req = 2 Ω; across 12 V, branch currents are 2 A and 4 A, total 6 A.","example":"Check that series voltage drops sum to the source and parallel branch currents sum to total current."},
{"heading":"Engineering use","body":"Voltage dividers provide a fraction of a source voltage; parallel circuits allow loads to share the same supply. Actual installations need correctly selected protection, conductors and enclosures."}
],["Series: same current; resistance adds.","Parallel: same voltage; conductance adds.","Use limiting cases to check results.","Circuit topology is determined by nodes, not drawing appearance."],
"Find the equivalent resistance of 10 Ω and 15 Ω in parallel.","Req = (10×15)/(10+15) = 6 Ω.",["Hambley — resistive networks."],practice="For 2 Ω and 7 Ω in series across 18 V, calculate current and each voltage drop."),
L("Electrical Fundamentals","Intermediate","4. Kirchhoff's Laws and Systematic Circuit Analysis",
"Kirchhoff's Current Law and Voltage Law express conservation of charge and energy in lumped circuit analysis.",
[
{"heading":"KCL at a node","body":"The algebraic sum of currents at a node is zero; total current entering equals total current leaving. Choose reference directions first and keep the signs consistent.","equation":r"\\sum I_k=0","example":"If 5 A and 1.5 A enter while 4 A and I leave: 5+1.5=4+I, so I=2.5 A."},
{"heading":"KVL around a loop","body":"The algebraic sum of voltage rises and drops around a closed loop is zero under the lumped-circuit model. Mark element polarities and follow one loop direction consistently.","equation":r"\\sum V_k=0","example":"A 12 V source and drops V1 and V2 give 12−V1−V2=0. If V1=4 V, then V2=8 V."},
{"heading":"Node-voltage method","body":"Choose a reference node (ground), assign unknown node voltages, and write KCL at each non-reference node. Express branch currents using element laws such as (Va−Vb)/R, then solve the simultaneous equations."},
{"heading":"Mesh-current method","body":"For a planar circuit, assign loop currents and write KVL around independent meshes. Shared components use the difference between mesh currents. After solving, validate signs, units and power balance."}
],["KCL conserves charge; KVL conserves energy in the model.","Choose reference directions and polarities before writing equations.","Negative current means the actual direction opposes the reference.","Verify equations and power balance."],
"At a node, 8 A enters while 3 A and 2 A leave. Find the remaining outgoing current.","8 = 3 + 2 + I, so I = 3 A leaving.",["Hambley — circuit laws and analysis."],practice="Write the KCL equation for a node connected to ground through 2 kΩ, to a 10 V node through 1 kΩ, and to a 4 V node through 4 kΩ."),
L("Electrical Fundamentals","Intermediate","5. AC Waveforms, RMS, Phasors and Power",
"Sinusoidal steady-state analysis represents alternating quantities with magnitude and phase. RMS values connect AC quantities to equivalent heating in resistive loads.",
[
{"heading":"Waveform quantities","body":"A sinusoid is v(t)=Vm sin(ωt+φ), where Vm is peak value, ω=2πf and f is frequency in hertz. Period T=1/f. Phase angle φ describes the waveform's displacement relative to a reference.","equation":r"\\omega=2\\pi f,\\qquad T=\\frac{1}{f}"},
{"heading":"RMS value","body":"RMS is the square root of the mean squared value over a period. For a pure sinusoid only, Vrms=Vm/√2 and Irms=Im/√2. This relationship does not apply to every waveform." ,"equation":r"V_{rms}=\\frac{V_m}{\\sqrt{2}}"},
{"heading":"Phasors and impedance","body":"A phasor represents the magnitude and phase of a sinusoid at one frequency. In sinusoidal steady state, resistance has impedance R, an ideal inductor has jωL, and an ideal capacitor has 1/(jωC). Impedance combines resistance and reactance." ,"equation":r"Z_R=R,\\quad Z_L=j\\omega L,\\quad Z_C=\\frac{1}{j\\omega C}"},
{"heading":"AC power","body":"For sinusoidal single-phase conditions, P=VI cosφ (W), Q=VI sinφ (var), S=VI (VA), and PF=P/S=cosφ. Distorted waveforms can require a more complete power-factor definition.","example":"At 230 V RMS, 5 A RMS and PF 0.8: P=230×5×0.8=920 W; S=1150 VA."}
],["Frequency and period are reciprocals.","RMS equals peak/√2 only for a pure sine wave.","Inductors and capacitors introduce phase shift.","Use RMS voltage/current in standard AC power formulas."],
"A 230 V RMS load draws 4 A at PF 0.75. Find real power.","P=VI PF=230×4×0.75=690 W, assuming the stated sinusoidal power-factor conditions.",["Hambley — AC circuits, phasors and power."],practice="Explain why a motor can draw substantial current while real power is lower than apparent power."),
L("Electrical Fundamentals","Advanced","6. First-Order RC Transients",
"Capacitors store energy in an electric field. Their voltage cannot change instantaneously in the ideal model, so switching produces a transient response governed by a time constant.",
[
{"heading":"Capacitor law and energy","body":"For capacitance C, i=C dv/dt and stored energy is E=½CV². A capacitor opposes rapid voltage change because a finite current is needed to change its voltage.","equation":r"i_C=C\\frac{dv_C}{dt},\\qquad E_C=\\frac12 CV_C^2"},
{"heading":"RC time constant","body":"For a first-order RC circuit, τ=Rth C, where Rth is the resistance seen by the capacitor with independent ideal voltage sources set to zero for the equivalent-resistance calculation. During charging toward a final value, the exponential response reaches about 63.2% of the total change after one time constant."},
{"heading":"General response","body":"For a first-order response, x(t)=xfinal+(xinitial−xfinal)e^(−t/τ). The same form applies to voltage or current variables when the circuit reduces to a first-order system and the initial/final values are defined correctly.","equation":r"x(t)=x_f+(x_0-x_f)e^{-t/\\tau}","example":"For R=10 kΩ and C=100 μF, τ=RC=1 s. After 1 s of charging from 0 toward 10 V, vC≈10(1−e⁻¹)=6.32 V."},
{"heading":"Design cautions","body":"Real capacitors have leakage, ESR, tolerance and voltage ratings. Stored charge can remain after disconnection. Discharge and verification must follow the equipment manufacturer's approved procedure; never assume a capacitor is safe because power has been switched off."}
],["Capacitor current depends on rate of voltage change.","τ=RthC for a simple RC circuit.","One τ corresponds to 63.2% of a step change.","Initial conditions and equivalent resistance matter."],
"For R=4.7 kΩ and C=220 μF, calculate the time constant.","τ=RC=4700×220×10⁻⁶≈1.034 s.",["Hambley — transient circuits."],practice="Estimate the capacitor voltage after 2τ when charging from 0 V toward 12 V.",safety="Capacitors may retain hazardous energy. Follow approved discharge and verification procedures; do not perform live work without authorization."),
L("Power Systems","Basic","1. Three-Phase Power and Connections",
"Three-phase systems use three sinusoidal voltages separated by 120 electrical degrees. They are efficient for generation and industrial power distribution.",
[
{"heading":"Balanced phases","body":"A balanced set has equal magnitudes and 120° phase displacement. In a balanced star connection, line voltage is √3 times phase voltage and line current equals phase current. In delta, line voltage equals phase voltage and line current is √3 times phase current."},
{"heading":"Power equations","body":"Using line-to-line RMS voltage and line current for a balanced load: S=√3 VL IL, P=√3 VL IL PF, and Q=√3 VL IL sinφ. These compact formulas assume balanced conditions and appropriate power-factor interpretation.","equation":r"P=\\sqrt{3}V_LI_LPF"},
{"heading":"Worked example","body":"A balanced 400 V system draws 10 A at PF 0.85. P≈1.732×400×10×0.85=5.89 kW. Confirm that the load is balanced and the measured quantities are line RMS values."},
{"heading":"Unbalance and harmonics","body":"Unbalanced loads can cause neutral current, voltage unbalance and additional heating. Nonlinear loads create harmonics that affect transformers, conductors, capacitors and protection. Detailed studies may require power-quality measurements and appropriate models."}
],["Know whether a value is line or phase quantity.","√3 formulas assume balanced three-phase operation.","PF affects real power but not the apparent-power formula.","Unbalance and harmonics require separate assessment."],
"Estimate real power for 400 V, 8 A and PF 0.9 balanced three-phase load.","P≈√3×400×8×0.9≈4.99 kW.",["Glover, Overbye & Sarma, Power System Analysis and Design."],practice="Explain the line/phase voltage relationship for a balanced star-connected source."),
L("Power Systems","Intermediate","2. Transformer and Substation Fundamentals",
"Transformers change AC voltage levels through mutual induction. Substations combine switching, transformation, protection, metering and control functions.",
[
{"heading":"Induction and turns ratio","body":"Changing primary current produces changing core flux, inducing EMF in windings. For an ideal transformer, Vp/Vs=Np/Ns and current ratio is inverse. Frequency remains the same.","equation":r"\\frac{V_p}{V_s}=\\frac{N_p}{N_s},\\qquad \\frac{I_p}{I_s}=\\frac{N_s}{N_p}"},
{"heading":"Equivalent circuit and losses","body":"Real transformers have winding resistance, leakage reactance, magnetizing current and core-loss components. Copper loss varies approximately with current squared; core loss depends strongly on voltage, frequency and core material. Efficiency is output power divided by input power."},
{"heading":"Substation functions","body":"Typical equipment may include transformers, circuit breakers, disconnectors, instrument transformers, surge arresters, busbars, earthing systems, relays and metering. The exact layout depends on voltage level, reliability needs, safety rules and utility standards."},
{"heading":"Example and checks","body":"A 11 kV/415 V transformer has an ideal ratio 11000/415≈26.5. Real voltage at the secondary depends on loading and regulation. Selection must also consider kVA rating, impedance, vector group, cooling, insulation, fault level and protection."}
],["Transformer ratio is a first approximation; real regulation matters.","Protection must coordinate with system fault levels.","Instrument transformers have specific burden and accuracy limits.","Use nameplates and manufacturer instructions."],
"What is the ideal secondary voltage of a 5:1 primary-to-secondary turns ratio with 200 V primary?","Vs=200×(1/5)=40 V AC.",["Chapman, Electric Machinery Fundamentals.","Glover, Overbye & Sarma, Power System Analysis and Design."],practice="List four nameplate or system factors beyond turns ratio that matter when selecting a transformer."),
L("Power Systems","Advanced","3. Short-Circuit Studies and Protection Coordination",
"Short-circuit analysis estimates fault currents so switchgear, conductors and protective devices can be selected and coordinated appropriately.",
[
{"heading":"Why calculate fault current?","body":"Fault current affects interrupting duty, thermal and mechanical stress, voltage depression and protection operation. A calculation needs source impedance, transformer impedance, cable/line impedance and system configuration."},
{"heading":"Per-unit method","body":"Per-unit quantities normalize electrical values to chosen base quantities. For three-phase systems, a common relationship is Zbase=Vbase²/Sbase when consistent line-to-line voltage and three-phase apparent-power bases are used. Per-unit analysis simplifies transformers and multi-voltage networks.","equation":r"Z_{base}=\\frac{V_{base}^2}{S_{base}},\\qquad Z_{pu}=\\frac{Z}{Z_{base}}"},
{"heading":"Coordination concepts","body":"Protection coordination aims for the protective device nearest a fault to operate first while upstream devices provide backup. Time-current curves, pickup settings, tolerances, inrush, motor starting and maximum/minimum fault levels must be considered."},
{"heading":"Engineering limitations","body":"A simplified three-phase fault estimate can use I≈Vphase/Zth at the fault point, but correct source equivalents, sequence networks, X/R ratio, motor contribution and standard calculation method may be needed. Use qualified engineering software and verify against applicable standards and equipment ratings."}
],["Fault current depends on the complete source-to-fault impedance.","Per-unit values simplify multi-voltage network calculations.","Coordination needs curves and real device data.","Never set protection solely from a simplified example."],
"Why must prospective short-circuit current be known before selecting a circuit breaker?","The breaker must have an adequate interrupting rating for the available fault current and must coordinate with conductors and upstream/downstream protection.",["Glover, Overbye & Sarma, Power System Analysis and Design.","Applicable current IEC/IEEE protection and switchgear standards."],practice="Explain the difference between interrupting rating and overload trip setting."),
L("Industrial Automation & Control","Basic","1. PLC Architecture and Scan Cycle",
"A PLC is an industrial controller that reads inputs, executes logic and updates outputs. Its predictable operation supports machinery and process automation.",
[
{"heading":"Hardware architecture","body":"A typical PLC has a power supply, CPU, memory, input/output modules and communication ports. Inputs can be pushbuttons, limit switches and sensors; outputs may command interface relays, contactors, valves or drives."},
{"heading":"Simplified scan","body":"A common scan model reads the input image, executes the program, updates outputs, then handles communication and diagnostics. Real controllers support tasks, interrupts and model-specific variations; the hardware manual defines actual behavior."},
{"heading":"Logic and interlocks","body":"Interlocks prevent incompatible actions and define permissive conditions. Ordinary PLC logic should not be assumed to provide a certified safety function. Safety functions require risk assessment and appropriately rated hardware/software."},
{"heading":"Testing workflow","body":"Define I/O, normal states, fault states, reset behavior and interlocks. Simulate where possible, test in a controlled environment, document revisions and verify the machine response before commissioning."}
],["Read the specific PLC manual.","Document inputs, outputs and fail states.","Separate process control from safety-related control.","Test changes under an approved commissioning plan."],
"What are the stages of a simplified PLC scan?","Read inputs, execute program, update outputs, then communications/housekeeping; exact sequence varies by controller.",["Petruzella, Programmable Logic Controllers.","Official PLC manufacturer programming manuals."],practice="Draw a simple text block diagram showing sensor inputs, PLC CPU and actuator outputs."),
L("Industrial Automation & Control","Intermediate","2. Sensors, 4–20 mA Loops and SCADA",
"Industrial automation connects physical measurements to control systems. Sensor selection and signal integrity are essential to reliable operation.",
[
{"heading":"Sensors and transducers","body":"A sensor detects a physical quantity such as temperature, pressure, level, position or flow. A transducer converts a physical quantity into a usable signal. Range, accuracy, repeatability, response time, environment and calibration matter."},
{"heading":"4–20 mA current loop","body":"A 4–20 mA signal commonly maps a process range linearly, with 4 mA representing the lower range and 20 mA the upper range. The 4 mA live zero helps distinguish a valid low measurement from some fault conditions, though actual fault interpretation depends on the transmitter and receiver.","example":"For a 0–100 °C range, 12 mA is halfway: (12−4)/(20−4)×100=50 °C."},
{"heading":"HMI and SCADA","body":"An HMI presents operator controls and values. SCADA supervises distributed assets through controllers, communication networks, alarms, trends and historical data. Alarm priorities should reflect consequence and operator response requirements."},
{"heading":"Reliability and cybersecurity","body":"Use shielded cabling and grounding methods specified by the equipment manufacturer. Segment industrial networks, restrict access, manage changes and use documented backups. Never bypass safety interlocks to silence an alarm."}
],["Check sensor range, wiring and scaling.","A 4–20 mA signal often uses 4 mA as live zero.","HMI/SCADA displays do not replace field verification.","Follow industrial cybersecurity and change-control policy."],
"A 4–20 mA transmitter represents 0–200 bar. What pressure corresponds to 16 mA?","(16−4)/(20−4)×200 = 150 bar.",["Petruzella, Programmable Logic Controllers.","Official transmitter, PLC and SCADA vendor documentation."],practice="List three checks for a reading that is stuck at 4 mA."),
L("Industrial Automation & Control","Advanced","3. VFDs, Motor Control and Commissioning",
"A variable-frequency drive controls AC motor speed by converting input power through a DC link and inverter stage. Correct setup requires matching the drive, motor and application.",
[
{"heading":"Operating principle","body":"A typical VFD rectifies AC to a DC link and switches semiconductor devices to synthesize a variable-frequency output. For an induction motor, synchronous speed is ns=120f/P rpm, where f is electrical frequency and P is pole count. Actual rotor speed is lower due to slip."},
{"heading":"Parameterization","body":"Important parameters include motor rated voltage, current, frequency, speed, acceleration/deceleration ramps, control mode, minimum/maximum speed and protection limits. Values must be taken from the actual motor nameplate and application requirements."},
{"heading":"Commissioning and fault finding","body":"Follow the manufacturer’s procedure, inspect wiring, confirm protective earthing and verify motor/load compatibility. Check fault codes, supply quality, cooling, load binding and parameter settings. DC-link capacitors may retain hazardous energy after isolation; obey specified waiting and verification procedures."},
{"heading":"System-level design","body":"Consider harmonics, EMC, cable length, motor insulation, bearing currents, braking energy, ventilation and protective coordination. A drive can change motor behavior and protection requirements; never select or configure it by horsepower alone."}
],["Synchronous speed depends on frequency and pole count.","Set motor parameters from the nameplate.","Review EMC, harmonics, cooling and braking requirements.","Follow isolation and DC-link discharge procedures."],
"A four-pole induction motor is supplied at 50 Hz. Calculate synchronous speed.","ns=120×50/4=1500 rpm. Actual rotor speed under load is lower due to slip.",["Chapman, Electric Machinery Fundamentals.","Official VFD and motor manufacturer manuals."],practice="List five nameplate/application items to verify before commissioning a VFD.",safety="Drive DC links may retain energy after disconnection. Follow the manufacturer's isolation, waiting and verification procedure."),
L("Electrical Machines","Intermediate","1. Transformer Operating Principle and Tests",
"Transformers transfer AC energy between windings by mutual induction. They change voltage and current levels while the supply frequency remains unchanged.",
[
{"heading":"Faraday's law","body":"A changing magnetic flux linking a winding induces EMF. For sinusoidal flux, the RMS induced EMF is approximately E=4.44 f N Φmax for a sinusoidal flux waveform. A conventional transformer must not be connected directly to DC because steady DC does not produce the intended alternating flux and can cause excessive current."},
{"heading":"Turns ratio","body":"For an ideal transformer, Vp/Vs=Np/Ns and current ratio is inverse. Real units include copper loss, core loss, leakage reactance and magnetizing current.","equation":r"\\frac{V_p}{V_s}=\\frac{N_p}{N_s}"},
{"heading":"Losses and efficiency","body":"Copper loss is approximately I²R in windings. Core loss includes hysteresis and eddy-current losses. Efficiency η=Pout/Pin×100%. Voltage regulation compares secondary voltage at no load and at a specified load, with the reference convention stated."},
{"heading":"Common tests","body":"Open-circuit tests estimate core loss and shunt parameters; short-circuit tests estimate series parameters and copper loss under test conditions. These are controlled tests for trained personnel using approved equipment and procedures."}
],["Transformer action requires changing flux.","Ideal current ratio is inverse to turns ratio.","Efficiency and regulation are distinct measures.","Testing requires correct isolation, grounding and approved procedures."],
"A transformer has 1000 primary turns and 100 secondary turns. At 230 V primary, estimate ideal secondary voltage.","Vs=230×100/1000=23 V AC.",["Chapman, Electric Machinery Fundamentals."],practice="Explain why an open-circuit test and short-circuit test reveal different equivalent-circuit parameters."),
L("Electrical Machines","Intermediate","2. Three-Phase Induction Motors",
"Induction motors convert electrical energy to mechanical energy through a rotating magnetic field and induced rotor currents.",
[
{"heading":"Rotating field and synchronous speed","body":"Balanced three-phase stator currents create a rotating magnetic field. Synchronous speed is ns=120f/P rpm. The rotor must have relative motion with respect to the field to induce rotor current and develop torque."},
{"heading":"Slip","body":"Slip is s=(ns−nr)/ns, where nr is rotor speed. At standstill s=1; in normal motoring operation, slip is small but nonzero. If rotor speed equalled synchronous speed, induced rotor EMF and torque would approach zero in the ideal induction principle.","equation":r"s=\\frac{n_s-n_r}{n_s}"},
{"heading":"Starting and loading","body":"Starting current can be several times rated current. Direct-on-line, star-delta, soft starter and VFD methods have different current, torque, cost and application characteristics. Selection depends on supply strength, load inertia, required starting torque and duty."},
{"heading":"Efficiency and maintenance","body":"Losses include stator and rotor copper losses, core losses, friction and windage. Maintenance includes condition monitoring, cooling, alignment, bearings, insulation and connections according to site procedure and manufacturer guidance."}
],["Synchronous speed depends on supply frequency and pole count.","Slip is necessary for induction-motor torque.","Starting method must fit the load and supply.","Use nameplate data and appropriate motor protection."],
"A 4-pole motor runs at 1440 rpm on 50 Hz. Find synchronous speed and slip.","ns=120×50/4=1500 rpm; s=(1500−1440)/1500=0.04=4%.",["Chapman, Electric Machinery Fundamentals."],practice="Compare DOL and VFD starting in terms of starting current and speed control."),
L("Electronics & Embedded Systems","Basic","1. Diodes, Rectifiers and Ripple",
"A diode conducts preferentially in one direction. Rectifier circuits convert AC into a unidirectional waveform used by DC supplies and many power-electronic systems.",
[
{"heading":"Diode behavior","body":"A practical semiconductor diode has a nonlinear current-voltage characteristic and a forward voltage that depends on device type, current and temperature. Reverse voltage and current are limited by device ratings."},
{"heading":"Half-wave and bridge rectifiers","body":"A half-wave rectifier uses one half-cycle. A full-wave bridge uses both half-cycles and normally has two conducting diode drops in its current path. The unfiltered average output depends on waveform and load."},
{"heading":"Filtering","body":"A capacitor across the load charges near waveform peaks and supplies current between peaks, reducing ripple. Larger capacitance or load resistance generally reduces ripple, but inrush current and component ratings must be considered.","example":"A simple approximate ripple estimate for a full-wave rectifier is ΔV≈Iload/(2fC), where f is mains frequency, assuming small ripple and a capacitor-input filter."},
{"heading":"Design checks","body":"Check reverse-voltage rating, peak current, thermal dissipation, capacitor voltage/ripple-current ratings, fusing, creepage/clearance and isolation requirements. Mains-powered supplies can contain lethal voltages and stored energy."}
],["Diodes are nonlinear devices.","Full-wave rectification uses both half-cycles.","Capacitor filters reduce ripple but increase peak charging current.","Ratings and isolation are critical."],
"What is the main benefit of a full-wave rectifier over a half-wave rectifier?","It uses both half-cycles, typically giving a higher average DC output and ripple at twice the supply frequency before filtering.",["Hambley — electronic devices and power supplies."],practice="Describe how increasing filter capacitance changes ripple and why it cannot be increased without considering ratings.",safety="Mains-powered electronics can retain hazardous charge. Do not probe or modify energized equipment without proper training and authorization."),
L("Electronics & Embedded Systems","Intermediate","2. MOSFET Switching and PWM",
"MOSFETs are voltage-controlled semiconductor devices widely used for switching power in converters, motor drives and embedded electronics.",
[
{"heading":"Switching operation","body":"A MOSFET's gate voltage controls channel conduction. In switching applications it is driven between an off state and a low-loss on state, subject to gate-drive, voltage, current and thermal limits. Switching losses occur during transitions."},
{"heading":"PWM concept","body":"Pulse-width modulation varies duty cycle to control average delivered energy. For an ideal low-frequency filtered DC load, average output may be approximated as D×Vdc for a simple unipolar chopper, where D is duty cycle from 0 to 1. Real topologies and inductive loads require their own models.","equation":r"D=\\frac{t_{on}}{T}"},
{"heading":"Gate drive and protection","body":"Gate charge, switching speed, parasitic inductance, dead time in bridge circuits, overcurrent protection and thermal design affect reliability. Inductive loads need an appropriate current path and transient suppression."},
{"heading":"Practical engineering","body":"Read the datasheet's safe operating area, RDS(on), gate charge, maximum junction temperature and transient limits. PCB layout and EMC matter because fast edges produce high di/dt and dv/dt."}
],["PWM controls duty cycle, not necessarily a linear voltage directly.","Switching loss and conduction loss both matter.","Inductive energy needs a controlled path.","Use datasheet limits and appropriate protection."],
"What does PWM duty cycle represent?","The fraction of each switching period for which the switch is commanded on: D=ton/T.",["Hambley — semiconductor devices and electronics.","Official semiconductor manufacturer datasheets."],practice="Explain why a flyback path or suitable clamp may be required when switching an inductive load."),
L("Installation & Maintenance","Basic","1. Electrical Drawings and Distribution Boards",
"Electrical drawings communicate circuit function, wiring, protection and equipment relationships. Reading them accurately is a core installation and maintenance skill.",
[
{"heading":"Common drawing types","body":"Single-line diagrams summarize power distribution using one line per circuit or system. Schematics show functional electrical relationships. Wiring diagrams show terminal-to-terminal connections; layout drawings show physical locations."},
{"heading":"Distribution board logic","body":"A distribution board typically contains an incoming supply, busbars, protective devices, neutral/earth arrangements appropriate to the system and outgoing circuits. Device type and ratings depend on load, prospective fault current, conductor capacity and local code."},
{"heading":"Drawing-reading workflow","body":"Confirm drawing number and revision, supply voltage, system earthing arrangement, circuit identifiers, protective device details and cross-references. Compare the drawing with the installation under approved procedures and report discrepancies."},
{"heading":"Documentation","body":"As-built drawings, circuit schedules, labels, test records and maintenance history help prevent unsafe assumptions. Never rely on a drawing alone as proof that a conductor is de-energized."}
],["Use the current revision of drawings.","Know the difference between schematic and wiring diagrams.","Labels support but do not replace verification.","Report mismatches and maintain records."],
"Why must drawings be checked against the actual installation?","Installations may have been modified, mislabeled or documented incorrectly. Verification prevents assumptions and supports safe planning.",["Applicable local wiring regulations and manufacturer documentation."],practice="List five details to confirm before planning work on a distribution circuit.",safety="Do not open or work inside live distribution equipment unless qualified and specifically authorized under approved procedures."),
L("Installation & Maintenance","Intermediate","2. Inspection, Testing and Fault-Finding",
"Reliable maintenance combines observation, safe isolation, measurement, logical diagnosis and documentation rather than replacing parts by guesswork.",
[
{"heading":"Plan and make safe","body":"Review the task, risk assessment, drawings and equipment history. Identify energy sources and stored energy; use approved isolation and verification procedures. Test instruments must be appropriate for the circuit category, voltage and environment."},
{"heading":"A structured fault-finding sequence","body":"Confirm the reported symptom; inspect visually from a safe state; compare with expected operation; divide the system into sections; test one hypothesis at a time; record readings; repair only within authorization; then function-test and document the result."},
{"heading":"Common measurement errors","body":"Wrong meter function, wrong terminals, poor contact, unsuitable range, incorrect reference point and instrument loading can produce misleading readings. Verify the instrument's condition and follow its manual."},
{"heading":"Maintenance types","body":"Corrective maintenance responds to failure; preventive maintenance follows a schedule; condition-based maintenance uses measured condition; predictive approaches estimate degradation trends. The right strategy depends on consequence, criticality and evidence."}
],["Use evidence-driven diagnosis.","Verify instrument function and rating.","Do not bypass protective devices to keep equipment running.","Record cause, action and verification."],
"What is the benefit of testing one hypothesis at a time?","It narrows the fault systematically, reduces unnecessary replacement and makes findings reproducible.",["Manufacturer service manuals and applicable inspection/testing standards."],practice="Create a fault-finding checklist for a motor that fails to start.",safety="Testing and fault-finding must be performed by qualified personnel under the site's approved safe-work process."),
L("Measurements & Instrumentation","Basic","1. Multimeters, Clamp Meters and Measurement Error",
"Measurements are only useful when the instrument, range, connection method and uncertainty suit the task.",
[
{"heading":"Instrument selection","body":"A digital multimeter may measure voltage, current, resistance and continuity. A clamp meter measures current by sensing the magnetic field around a conductor; AC/DC capability depends on the instrument. A clamp around both line and return may cancel the field in a two-wire circuit."},
{"heading":"Voltage and current connection","body":"Voltage is measured in parallel with a circuit; conventional current measurement requires a series path or a suitable clamp instrument. Connecting a meter in current mode directly across a voltage source can cause a short circuit and injury."},
{"heading":"Accuracy and uncertainty","body":"Instrument accuracy specifications may include a percentage of reading plus a count term. Resolution is the smallest displayed increment and is not the same as accuracy. Calibration status, temperature and lead condition affect confidence."},
{"heading":"Safe measurement","body":"Inspect the instrument, leads, fuses and category rating. Select the correct function and terminals before connection. Follow the manufacturer's instructions and site procedures; live measurement is only for appropriately trained and authorized people."}
],["Voltage is measured in parallel; current in series or by suitable clamp.","Resolution is not accuracy.","Check meter category and lead ratings.","Never place a current-mode meter across a voltage source."],
"Why should a multimeter in current mode not be placed directly across a voltage source?","Its current input has very low resistance, potentially creating a short circuit, damaging the meter and causing injury.",["Manufacturer instrument manuals and calibration documentation."],practice="Explain the difference between resolution, accuracy and repeatability.",safety="Live measurements can be hazardous. Only qualified and authorized people should perform them using approved procedures."),
L("Measurements & Instrumentation","Intermediate","2. Sensors, Calibration and 4–20 mA",
"Instrumentation converts physical conditions into signals that can be measured, displayed and used by control systems.",
[
{"heading":"Sensor characteristics","body":"Range, span, sensitivity, accuracy, repeatability, hysteresis, linearity, drift and response time describe different aspects of performance. Select a sensor for process range, medium, environment and required uncertainty."},
{"heading":"Linear scaling","body":"For a linear transmitter mapping a lower range value LRV to an upper range value URV, process value = LRV + (I−4 mA)/16 mA × (URV−LRV), for a standard 4–20 mA mapping.","example":"For a 0–100 °C transmitter, 12 mA maps to 50 °C."},
{"heading":"Calibration","body":"Calibration compares an instrument's indication with a reference of known uncertainty. Adjustment is a separate action. Calibration records should include as-found/as-left readings where applicable, reference equipment, conditions and traceability."},
{"heading":"Fault diagnosis","body":"Check supply, loop polarity, wiring continuity, configured range, input scaling and transmitter diagnostics. A signal at 4 mA may be a valid lower-range measurement; fault currents or diagnostics depend on device configuration."}
],["Calibration is comparison; adjustment changes the instrument.","Scaling must match the configured range.","Loop diagnostics are device-specific.","Document calibration results and uncertainty."],
"A 4–20 mA transmitter represents 0–200 bar. What value corresponds to 16 mA?","Value = (16−4)/16×200 = 150 bar.",["Official transmitter and controller manuals.","Relevant metrology and calibration procedures."],practice="List possible causes of a displayed value that is consistently twice the expected measurement."),
L("Renewable Energy","Basic","1. Photovoltaic Modules and Array Configuration",
"PV cells convert light into DC electrical energy. Modules and arrays must be configured within voltage, current, temperature and equipment constraints.",
[
{"heading":"Cell to array","body":"Cells form modules; modules form strings and arrays. Series connection adds voltage while current is limited by the string path; parallel connection adds current while voltage remains similar. Mismatch and shading can reduce output and activate bypass diodes."},
{"heading":"I–V and P–V curves","body":"Current and voltage vary with irradiance and cell temperature. Maximum power occurs at the operating point where P=VI is highest. Open-circuit voltage and short-circuit current are distinct module ratings and are measured under specified conditions."},
{"heading":"MPPT and energy estimate","body":"Maximum Power Point Tracking adjusts the operating point as sunlight and temperature change. A rough daily energy estimate is array kW × equivalent peak-sun-hours × performance ratio; site-specific simulation is needed for credible design."},
{"heading":"System safety","body":"PV strings may remain energized in daylight. DC isolation, suitable connectors, protection, bonding, surge protection and correct cable selection must follow applicable standards and manufacturer instructions."}
],["Series increases voltage; parallel increases current.","Temperature affects voltage and irradiance affects current strongly.","MPPT seeks maximum available power.","DC PV hazards require specific protection and procedures."],
"What does MPPT do?","It adjusts the operating point to extract power near the PV array's maximum-power point under changing conditions.",["PV module and inverter manufacturer datasheets.","Applicable current electrical and grid-connection standards."],practice="Estimate daily energy from a 5 kW array, 4.5 peak-sun-hours and performance ratio 0.8."),
L("Renewable Energy","Intermediate","2. Batteries, Inverters and System Sizing",
"Energy storage and power conversion are selected from load requirements, autonomy, efficiency, chemistry, environment and safety constraints.",
[
{"heading":"Energy and power","body":"Power (kW) describes the rate of energy transfer; capacity (kWh) describes stored energy. A battery's usable energy is below nominal energy when depth-of-discharge limits and conversion losses are included."},
{"heading":"Simple sizing estimate","body":"Required nominal battery energy can be estimated as daily load energy × autonomy days divided by usable depth-of-discharge and system efficiency. This is a first-pass estimate only; discharge rate, temperature, ageing, reserve and manufacturer limits matter.","example":"For 4 kWh/day, 1 day autonomy, 80% usable depth and 90% efficiency: nominal energy ≈4/(0.8×0.9)=5.56 kWh."},
{"heading":"Inverter selection","body":"Check continuous power, surge capability, input voltage window, waveform, efficiency, temperature derating, grid requirements and compatible battery chemistry. Motor starting and nonlinear loads can require additional capacity."},
{"heading":"Protection and operation","body":"Battery systems require appropriate overcurrent protection, isolation, ventilation or thermal controls as applicable, cable sizing, BMS integration and manufacturer-approved installation. Do not mix batteries or chargers outside approved compatibility."}
],["kW is power; kWh is energy.","Usable battery energy is lower than nominal capacity.","Include conversion losses and reserve.","Follow battery and inverter manufacturer safety instructions."],
"A load uses 3 kWh/day. Estimate nominal battery energy for one day autonomy, 80% usable depth and 90% efficiency.","E = 3/(0.8×0.9) ≈ 4.17 kWh, before extra reserve, ageing and rate considerations.",["Official battery and inverter manufacturer design manuals."],practice="List four reasons actual battery capacity can differ from a simple kWh calculation.",safety="Battery systems can deliver very high fault current and may present chemical or thermal hazards. Use approved equipment and qualified installation."),
L("Electrical Design & Calculations","Intermediate","1. Load Estimation and Demand",
"Electrical design begins by identifying connected loads, expected operating conditions and applicable demand/diversity rules.",
[
{"heading":"Connected load versus demand","body":"Connected load is the sum of rated loads. Maximum demand is the highest expected simultaneous demand over the defined period. Diversity recognizes that not every load necessarily operates at full rating simultaneously, but must be applied only where permitted and justified."},
{"heading":"Power and current","body":"For single-phase resistive loads, I≈P/V. For single-phase AC where P is real input power, I≈P/(V PF). For balanced three-phase loads, I≈P/(√3 VL PF). Motor efficiency must be included when P refers to mechanical output rather than electrical input."},
{"heading":"Worked example","body":"A 2 kW single-phase load at 230 V and PF 0.9 draws approximately I=2000/(230×0.9)=9.66 A, assuming 2 kW is electrical real input power."},
{"heading":"Design verification","body":"Current calculations alone do not select a cable or breaker. Check installation method, ambient temperature, grouping, insulation, voltage drop, short-circuit withstand, disconnection times and local code requirements."}
],["Define what the stated power represents.","Include power factor and efficiency when appropriate.","Demand factors need justification and code support.","Cable and protection design require multiple checks."],
"A 3 kW single-phase electrical load operates at 230 V and PF 1. Estimate current.","I=P/V=3000/230≈13.04 A.",["Applicable local wiring regulations and engineering design guides."],practice="Explain why a cable carrying 15 A cannot be selected from current alone."),
L("Electrical Design & Calculations","Advanced","2. Voltage Drop and Cable Selection Workflow",
"Voltage drop and conductor selection depend on load current, conductor impedance, length, temperature, installation conditions and code limits.",
[
{"heading":"Basic DC estimate","body":"For a two-wire DC circuit, loop resistance is approximately ρ(2L)/A and voltage drop ΔV=IRloop. Use consistent units and the actual conductor resistivity at operating temperature for a credible calculation.","equation":r"\\Delta V=I\\frac{2\\rho L}{A}"},
{"heading":"AC cable considerations","body":"For AC circuits, resistance and reactance can both matter; three-phase voltage drop also depends on phase geometry and power factor. Published manufacturer tables or approved design methods are preferable for final calculations."},
{"heading":"Ampacity and correction factors","body":"Current-carrying capacity depends on conductor material, insulation temperature rating, installation method, ambient temperature, grouping, thermal insulation and harmonic content. Correction factors must follow the applicable standard and exact conditions."},
{"heading":"Complete selection checklist","body":"Confirm design current, protective-device coordination, cable ampacity after correction factors, voltage drop, fault-loop impedance/disconnection, short-circuit thermal withstand, mechanical protection, environmental rating and local code requirements. Document assumptions and calculations."}
],["A voltage-drop formula is only one part of cable selection.","Use consistent units and temperature assumptions.","Installation conditions affect ampacity.","Final design must follow current local regulations and qualified review."],
"Why is voltage-drop compliance alone insufficient to prove that a cable is correctly selected?","Ampacity, fault withstand, disconnection, installation conditions, environmental suitability and protective-device coordination must also be checked.",["Applicable current wiring rules and cable manufacturer tables."],practice="Prepare a design checklist for a 30 m circuit supplying a motor; list the data you would need before calculating."),
L("Control Systems & Drives","Intermediate","1. Feedback and PID Control",
"Feedback control compares a measured output with a setpoint and adjusts a controller output to reduce error.",
[
{"heading":"Open and closed loop","body":"Open-loop control does not use output feedback. Closed-loop control measures the process variable and compares it with the setpoint. Feedback can reject disturbances but poor tuning or delays can cause oscillation."},
{"heading":"PID terms","body":"A PID controller combines proportional action on current error, integral action on accumulated error and derivative action on the rate of error change. P responds to error, I can remove steady-state offset, and D can anticipate rapid changes but is sensitive to measurement noise.","equation":r"u(t)=K_pe(t)+K_i\\int e(t)dt+K_d\\frac{de(t)}{dt}"},
{"heading":"Practical tuning","body":"Tune only within an approved process procedure. Begin from documented baseline settings, change one parameter at a time, trend setpoint/process/output, and watch for saturation, oscillation and actuator limits. Derivative filtering and anti-windup may be needed."},
{"heading":"System limits","body":"Sensor delay, actuator deadband, process nonlinearity, sample time and safety interlocks affect control quality. A control loop is not a substitute for independent protective systems where risk assessment requires them."}
],["Feedback uses measured output.","Integral action can remove steady-state offset but may cause windup.","Derivative action is noise-sensitive.","Use documented, safe tuning procedures."],
"What is the usual purpose of integral action in a PID controller?","It accumulates error and can remove steady-state offset, although excessive integral action can cause overshoot or windup.",["Control-systems textbooks and official controller manuals."],practice="Explain how a long sensor delay can affect closed-loop stability."),
L("Control Systems & Drives","Advanced","2. Motor Drives and Dynamic Performance",
"Motor-drive systems couple electrical conversion, control algorithms and mechanical loads. Performance depends on motor type, load torque and drive limits.",
[
{"heading":"Load and speed","body":"Mechanical power is P=Tω, where T is torque and ω is angular speed in rad/s. Constant-torque and variable-torque loads impose different demands. Fans and pumps often have torque that rises approximately with speed squared and power approximately with speed cubed in ideal affinity-law conditions."},
{"heading":"Drive control modes","body":"Scalar V/f control maintains an approximate voltage-to-frequency relationship for basic induction-motor speed control. Vector control estimates or measures motor flux and torque-producing current for better dynamic performance. Exact capabilities depend on the drive and motor."},
{"heading":"Braking and regeneration","body":"Deceleration returns or dissipates mechanical energy. Depending on the drive, braking may use a resistor, regenerative front end or other approved method. A short deceleration time can overvoltage the DC link or exceed mechanical limits."},
{"heading":"Commissioning checks","body":"Verify motor and load data, wiring, grounding, rotation, acceleration/deceleration, thermal protection, emergency stopping architecture, EMC and application-specific limits. Follow the manufacturer's approved procedure."}
],["Mechanical power equals torque times angular speed.","Load characteristics affect drive sizing.","Braking energy must be managed.","Safety functions and emergency stopping require proper system design."],
"A shaft delivers 20 N·m at 1500 rpm. Estimate mechanical power.","ω=2π×1500/60≈157.1 rad/s; P=Tω≈20×157.1=3.14 kW.",["Chapman, Electric Machinery Fundamentals.","Official motor-drive application guides."],practice="Explain why a fan may save substantial energy when speed is reduced, under affinity-law assumptions."),
L("Electrical Safety & Standards","Basic","1. Electrical Hazards and Safe Isolation Principles",
"Electrical safety is a planned system of controls, not a single device or warning label. Shock, arc flash, fire and unexpected motion can cause severe harm.",
[
{"heading":"Hazard recognition","body":"Risk depends on voltage, fault energy, exposure, environment, equipment condition and task. Stored energy can remain in capacitors, batteries, rotating machinery and other systems after the supply is removed."},
{"heading":"Isolation and verification","body":"Follow the site's approved procedure: identify every source, isolate using approved devices, prevent reconnection, and verify the safe state with appropriately rated equipment and the required proving process. A control switch or indicator light alone does not prove isolation."},
{"heading":"Layered protection","body":"Insulation, enclosures, protective earthing, overcurrent devices, residual-current protection, barriers, interlocks and safe work practices address different hazards. Correct device selection and maintenance are essential."},
{"heading":"Stop-work triggers","body":"Stop and seek qualified supervision if the isolation is uncertain, drawings conflict with the installation, equipment is damaged, conditions change, or the task exceeds your training and authorization. Never bypass protective devices as a workaround."}
],["Use approved risk assessment and isolation procedures.","Verify isolation; do not rely on a switch position.","Use instruments rated for the task.","Training text does not authorize electrical work."],
"Why is a switch being OFF not enough proof that a circuit is safe?","There may be alternate supplies, backfeed, incorrect labels, a failed switch or stored energy. Approved isolation and verification are required.",["Applicable local electrical regulations and workplace safety procedures.","Relevant current IEC/IEEE standards."],safety="This is awareness education, not authorization to work on electrical equipment. Follow local laws, site procedures and qualified supervision."),
L("Electrical Safety & Standards","Intermediate","2. Protective Earthing and Residual-Current Protection",
"Protective measures are designed to reduce risk when insulation fails or a fault occurs. Their application depends on system earthing arrangement and local requirements.",
[
{"heading":"Protective earthing","body":"Protective earthing connects exposed conductive parts to the protective earthing system so a fault can produce a current path that supports automatic disconnection where the design requires it. Earthing is not a guarantee of zero touch voltage in every fault."},
{"heading":"Overcurrent protection","body":"Fuses and circuit breakers protect against specified overload and short-circuit conditions. Selection considers conductor capacity, prospective fault current, breaking capacity, time-current behavior and coordination."},
{"heading":"Residual-current devices","body":"An RCD detects an imbalance between currents in live conductors and disconnects when its operating criteria are met. It does not replace overcurrent protection unless the device combines both functions, and it does not protect against every possible shock scenario."},
{"heading":"Verification","body":"Inspection and tests depend on the system and applicable code, and may include continuity, insulation resistance, polarity, earth-fault loop impedance and RCD operation. These tests require qualified personnel and suitable instruments."}
],["Earthing and bonding are distinct but related concepts.","RCDs do not replace all other protective measures.","Breaking capacity must suit available fault current.","Testing must follow applicable standards and safe procedures."],
"What protection does an RCD provide, and what does it not automatically replace?","It detects residual-current imbalance and disconnects under specified conditions. It does not automatically replace overload/short-circuit protection or guarantee protection from every shock condition.",["Applicable current IEC 60364 series and local wiring regulations; verify edition and jurisdiction."],practice="Explain why protective earthing and overcurrent protection are often designed together."),
L("Marine Electrical & ETO","Intermediate","1. Shipboard Generation and Distribution",
"Shipboard electrical systems provide power to propulsion auxiliaries, navigation, accommodation, cargo systems and essential services. Reliability and redundancy are major design concerns.",
[
{"heading":"Generation and main switchboard","body":"Ships commonly use generator sets feeding a main switchboard, with distribution to essential and non-essential loads. Actual voltage, frequency, generator count and architecture depend on vessel type and design."},
{"heading":"Parallel operation","body":"Generators operating in parallel need compatible voltage, frequency, phase sequence and phase angle before breaker closing. Load sharing typically separates active-power/frequency behavior from reactive-power/voltage behavior, depending on governor and AVR controls."},
{"heading":"Emergency power","body":"Emergency sources supply designated services if normal power is lost. Their location, starting method, endurance and loads are regulated by applicable maritime rules and vessel design. Exact requirements must be verified for vessel class and flag state."},
{"heading":"Maintenance and documentation","body":"Planned maintenance, insulation monitoring where applicable, switchboard inspections, protection testing and accurate records support reliability. Work requires shipboard procedures, permits and authorization."}
],["Shipboard distribution is designed around service criticality and redundancy.","Synchronizing requires voltage, frequency, phase sequence and phase-angle checks.","Emergency systems have vessel- and regulation-specific requirements.","Follow shipboard procedures and current maritime rules."],
"What must be checked before synchronizing a generator to a live bus?","Voltage, frequency, phase sequence and phase angle must be within the permitted synchronizing conditions, using the approved system and procedure.",["Chapman — electrical machines.","Applicable SOLAS/STCW requirements and flag-state guidance; verify current official texts."],practice="Explain why essential and non-essential loads may be treated differently."),
L("Marine Electrical & ETO","Advanced","2. Shipboard Fault Response and ETO Career Readiness",
"Marine electro-technical work combines electrical machines, distribution, automation, instrumentation, safety, documentation and maritime certification requirements.",
[
{"heading":"Fault response","body":"A disciplined response starts by protecting people and the vessel, following bridge/engine-room communication and emergency procedures, identifying the affected system and avoiding unauthorized resets that could worsen the fault. Restore services only within authority and documented procedure."},
{"heading":"System knowledge","body":"ETO-related competence may involve generators, switchboards, motors, drives, alarms, sensors, batteries, navigation/communication equipment and planned maintenance. Duties and authority depend on certificate, vessel and employer."},
{"heading":"Certification pathway","body":"STCW requirements, medical fitness, approved training, sea service, assessment and certificate endorsement depend on the competent maritime authority and vessel/flag-state context. Do not rely on social-media claims or unofficial promises; confirm current requirements with the official authority and approved provider."},
{"heading":"Sponsorship and job verification","body":"Check company registration, vessel/employer legitimacy, written training terms, who pays fees, refund clauses, sea-service arrangements and the exact job offered. Never treat a training payment alone as a guaranteed ship placement."}
],["Safety and vessel operations come first.","Follow command structure and emergency procedures.","Certification requirements must be verified with the competent authority.","Get sponsorship and employment terms in writing."],
"What should a candidate verify before accepting an ETO training sponsorship?","Verify the employer and provider, official approval, exact costs covered, refund/repayment conditions, required sea service, certificate pathway and whether the shipboard placement is a written commitment.",["Official maritime administration and approved training-provider guidance.","Current STCW Convention/Code requirements as implemented by the competent authority."],practice="Draft a checklist of questions to ask a company offering ETO sponsorship.",safety="This lesson is career information, not official certification advice. Confirm requirements with the competent maritime authority and approved training providers.")
]

QUIZ_BANK = {
"Electrical Fundamentals":[
{"question":"Which quantity is measured in amperes?","options":["Voltage","Current","Resistance","Energy"],"answer":"Current","explanation":"Current is the rate of charge flow."},
{"question":"A 12 V source is across 4 Ω. Ideal current?","options":["0.33 A","3 A","16 A","48 A"],"answer":"3 A","explanation":"I=V/R=12/4=3 A."},
{"question":"6 Ω and 3 Ω in parallel equal:","options":["9 Ω","4.5 Ω","2 Ω","18 Ω"],"answer":"2 Ω","explanation":"Req=(6×3)/(6+3)=2 Ω."},
{"question":"A 2 A current flows for 5 s. Charge is:","options":["2.5 C","7 C","10 C","20 C"],"answer":"10 C","explanation":"Q=It=10 C."},
{"question":"For a pure sinusoid, RMS voltage is:","options":["Peak × √2","Peak / √2","Peak / 2π","Always equal to peak"],"answer":"Peak / √2","explanation":"This relation applies to a pure sinusoid."}],
"Power Systems":[
{"question":"Balanced three-phase real power can be estimated using:","options":["P=V/I","P=√3 VL IL PF","P=I/R","P=f/T"],"answer":"P=√3 VL IL PF","explanation":"Use line-to-line RMS voltage and line current for a balanced load."},
{"question":"What does per-unit analysis do?","options":["Removes all losses","Normalizes quantities to base values","Measures frequency only","Replaces protection"],"answer":"Normalizes quantities to base values","explanation":"Per-unit values simplify multi-voltage system analysis."}],
"Industrial Automation":[
{"question":"Which is a common PLC scan stage?","options":["Read inputs","Burn memory","Remove earthing","Ignore outputs"],"answer":"Read inputs","explanation":"A simplified scan reads inputs, executes logic and updates outputs."},
{"question":"A 4–20 mA signal represents 0–100 °C. What is 12 mA?","options":["25 °C","50 °C","75 °C","100 °C"],"answer":"50 °C","explanation":"12 mA is halfway between 4 and 20 mA."}],
"Electrical Machines":[
{"question":"A 4-pole motor on 50 Hz has synchronous speed:","options":["750 rpm","1000 rpm","1500 rpm","3000 rpm"],"answer":"1500 rpm","explanation":"ns=120f/P=120×50/4."},
{"question":"A conventional transformer relies on:","options":["Steady DC flux only","Changing magnetic flux","Friction","Chemical reaction"],"answer":"Changing magnetic flux","explanation":"Changing flux induces EMF in the secondary."}],
"Electronics & Embedded Systems":[
{"question":"A full-wave rectifier uses:","options":["Only positive half-cycle","Both half-cycles","No diodes","Only DC input"],"answer":"Both half-cycles","explanation":"It rectifies both halves of the AC waveform."}],
"Installation & Maintenance":[
{"question":"A drawing alone proves a circuit is de-energized.","options":["True","False"],"answer":"False","explanation":"The actual installation and approved isolation must be verified."}],
"Measurements & Instrumentation":[
{"question":"A current-mode multimeter should be placed directly across a voltage source.","options":["True","False"],"answer":"False","explanation":"This can create a short circuit and damage equipment or cause injury."}],
"Renewable Energy":[
{"question":"MPPT is used to:","options":["Track maximum PV power point","Increase grid frequency","Replace all protection","Measure cable length"],"answer":"Track maximum PV power point","explanation":"It adjusts operating conditions to extract available PV power."}],
"Electrical Design & Calculations":[
{"question":"Cable selection is determined by current alone.","options":["True","False"],"answer":"False","explanation":"Ampacity, installation, voltage drop, fault withstand and protection also matter."}],
"Control Systems & Drives":[
{"question":"Integral action in PID control can help:","options":["Remove steady-state offset","Measure cable resistance","Change pole count","Replace emergency protection"],"answer":"Remove steady-state offset","explanation":"Integral action accumulates error, but excessive action may cause windup."}],
"Electrical Safety & Standards":[
{"question":"A switch in OFF position proves the circuit safe to touch.","options":["True","False"],"answer":"False","explanation":"Approved isolation and verification are required."}],
"Marine Electrical & ETO":[
{"question":"Before generator synchronizing, which condition is not required?","options":["Voltage compatibility","Frequency compatibility","Phase sequence check","Paint color match"],"answer":"Paint color match","explanation":"Electrical synchronizing conditions include voltage, frequency, phase sequence and phase angle."}]
}

GLOSSARY = {
"AC — Alternating Current":"Current that changes with time and periodically reverses direction in common AC systems.",
"ADC — Analog-to-Digital Converter":"Circuit that converts an analog input into a digital representation.",
"Ampere (A)":"SI unit of electric current.",
"Apparent power (VA)":"Product of RMS voltage and current in the stated AC system; in balanced three-phase systems S=√3 VL IL.",
"Capacitance (F)":"Ability to store charge per unit voltage.",
"Contactor":"Electrically controlled switching device commonly used for power circuits.",
"DC — Direct Current":"Current that flows in one direction, though its magnitude may vary.",
"ETO":"Electro-Technical Officer; shipboard role subject to applicable maritime certification requirements.",
"Frequency (Hz)":"Number of cycles per second.",
"Impedance (Ω)":"Complex opposition to sinusoidal AC, combining resistance and reactance.",
"Inductance (H)":"Property relating induced voltage to the rate of change of current.",
"Insulation resistance":"Resistance of insulation measured using an appropriate test method and instrument.",
"Kirchhoff's Current Law":"Algebraic sum of currents at a node is zero.",
"Kirchhoff's Voltage Law":"Algebraic sum of voltages around a closed loop is zero in the lumped-circuit model.",
"PLC":"Programmable Logic Controller, an industrial controller for automation.",
"Power factor":"Ratio of real power to apparent power under the relevant definitions.",
"RCD":"Residual Current Device; detects residual-current imbalance and disconnects under specified conditions.",
"Resistance (Ω)":"Opposition to current flow.",
"RMS":"Root-mean-square value; for a pure sinusoid, RMS equals peak divided by √2.",
"SCADA":"Supervisory Control and Data Acquisition system.",
"Transformer":"Device that transfers AC energy between windings through changing magnetic flux.",
"VFD":"Variable Frequency Drive; controls AC motor operation by adjusting output frequency and voltage as appropriate.",
"Voltage (V)":"Electric potential difference; energy transferred per unit charge.",
"Watt (W)":"SI unit of power.",
}

REFERENCES = [
{"title":"Electrical Engineering: Principles and Applications","author":"Allan R. Hambley","use":"Foundational circuit theory, electrical devices, systems and applications."},
{"title":"Electric Machinery Fundamentals","author":"Stephen J. Chapman","use":"Transformers, motors, generators, equivalent circuits and machine performance."},
{"title":"Power System Analysis and Design","author":"J. Duncan Glover, Thomas Overbye and Mulukutla S. Sarma","use":"Power-system models, fault studies, transmission and analysis."},
{"title":"Programmable Logic Controllers","author":"Frank D. Petruzella","use":"PLC architecture, programming concepts and industrial control."},
{"title":"IEC Electropedia — International Electrotechnical Vocabulary","author":"International Electrotechnical Commission","use":"Terminology and definitions for electrical and electrotechnical concepts.","url":"https://www.electropedia.org/"},
{"title":"IEC standards catalogue","author":"International Electrotechnical Commission","use":"Check current relevant standards and editions for the applicable jurisdiction.","url":"https://www.iec.ch/standards"},
{"title":"IEEE Standards Association","author":"IEEE","use":"Standards resources for power, electrical, control and instrumentation engineering.","url":"https://standards.ieee.org/"},
{"title":"STCW information","author":"International Maritime Organization","use":"Official maritime training and certification convention information; also confirm local implementation with the competent authority.","url":"https://www.imo.org/"},
{"title":"Manufacturer technical manuals","author":"Relevant equipment manufacturer","use":"Use the exact model's datasheet, installation instructions, commissioning manual and safety notices."},
]
